version: '3.8'

services:
  app:
    image: ki_pipeline:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8080:80"
